# Generated by Django 5.0.1 on 2024-01-24 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_card_product_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='product_type',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('shoes', 'Shoes')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
